# Generated by Django 5.1.1 on 2024-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_provider',
            fields=[
                ('providerName', models.CharField(max_length=100, null=True)),
                ('businessName', models.CharField(max_length=100, null=True)),
                ('providerContact', models.IntegerField(null=True)),
                ('providerEmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('providerAddress', models.TextField(null=True)),
                ('providerCity', models.CharField(max_length=100, null=True)),
                ('providerPin', models.IntegerField(null=True)),
                ('providerAvgCharge', models.IntegerField(null=True)),
                ('providerDetails', models.TextField(null=True)),
                ('providerServiceImage', models.ImageField(null=True, upload_to='static/service/')),
                ('providerAvlDays', models.IntegerField(null=True)),
                ('providerSvcDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=22, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('address', models.TextField(null=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/profilepicture/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='static/slider/')),
                ('title', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
