# Generated by Django 5.1.1 on 2024-09-23 12:11

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_provider_tbl_register_tbl_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, null=True)),
                ('provider_picture', models.ImageField(null=True, upload_to='static/provider/')),
                ('avg_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('service_name', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(null=True)),
                ('availability', tinymce.models.HTMLField(null=True)),
                ('provider_mobile', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('service_picture', models.ImageField(null=True, upload_to='static/service/')),
                ('pincode', models.IntegerField()),
                ('added_date', models.DateField(null=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_provider',
        ),
    ]
