# Generated by Django 5.1.1 on 2024-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tbl_service_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('providerid', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=40, null=True)),
                ('detail', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('payment', models.IntegerField(null=True)),
                ('reqdate', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
