# Generated by Django 5.1.1 on 2024-10-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
